# build-project.yml
name: Build with Gradle

on:
  push:
    branches: [ "master" ] # Acionado a cada push na branch 'master'
  pull_request:
    branches: [ "master" ] # Acionado em pull requests para a 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # O build.gradle.kts especifica o Java 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # O comando 'build' executa a compilação, testes e outras checagens.
        # A tarefa 'shadowJar' também é executada pelo 'build' graças à configuração do projeto.
        run: ./gradlew build
