# release.yml
name: Create Release

# Este workflow é acionado quando uma nova tag é enviada (pelo sync ou manualmente)
on:
  push:
    tags:
      - '*' # Aciona para qualquer tag
  workflow_dispatch:
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      # Permissão necessária para criar releases
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # O nome da tag que acionou o workflow fica disponível em github.ref_name
      - name: Get Original Release Info
        id: get_release
        run: |
          # Try to fetch the official release notes from the upstream repository's tag.
          # The "|| true" part ensures that if the command fails (e.g., 404 Not Found), the script doesn't exit.
          CHANGELOG_BODY=$(gh api repos/alexdev03/UnlimitedNametags/releases/tags/${{ github.ref_name }} --jq '.body' 2>/dev/null) || true

          # If the command failed or returned an empty body, use a fallback message.
          if [[ -z "$CHANGELOG_BODY" ]]; then
            CHANGELOG_BODY="No official changelog was found for this tag. Please check the commit history for details."
          fi
          
          # Use a heredoc to safely output the changelog to the next steps.
          cat <<EOF >> "$GITHUB_OUTPUT"
          changelog<<HEREDOC
          $CHANGELOG_BODY
          HEREDOC
          EOF
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # O corpo da release será o changelog que pegamos do repositório original
          body: ${{ steps.get_release.outputs.changelog }}
          # Anexa o .jar gerado que está na pasta target
          files: target/*.jar
