# sync-fork.yml
name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/alexdev03/UnlimitedNametags.git

      - name: Sync Tags and Branch
        run: |
          # Sincroniza a branch main
          git fetch upstream --prune
          git checkout main
          git merge upstream/main
          git push origin main
          
          # Sincroniza todas as tags do upstream para o seu fork
          git fetch upstream --tags --force
          git push origin --tags --force
